name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v7.0.0
      - uses: ruby/setup-ruby@v1.314.0
        with:
          ruby-version: "3.4"

      - run: bundle config set --local without 'benchmarks'
      - run: bundle install
      - run: make
      - run: make install
      - run: rake test
      - run: rake examples
      - run: gem build uber_fast_excel.gemspec

      - name: Publish to RubyGems
        uses: rubygems/release-gem@v1.4.0
